# odleglosc po ktorej robot wykona zdjecia, w cm
co_ile_sfera: 800

# w cm
wielkosc_swiata: 1

#w wcm
wielkosc_komorki: 1

#w cm
dystans_od_sciany:
    srodek_pola: 1
    szerokosc_pola: 1

#
algorytm: najlepszy
